'use client';

import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Award,
  Ban,
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Check,
  CheckCheck,
  Clock3,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CheckCircle2,
  CircleEllipsis,
  CircleHelp,
  CircleX,
  Coins,
  Cookie,
  CreditCard,
  Database,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Handshake,
  Headset,
  HeartPulse,
  Home,
  Info,
  LayoutDashboard,
  Layers3,
  List,
  LoaderCircle,
  Lock,
  LockKeyholeOpen,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircleMore,
  MousePointer2,
  Phone,
  PieChart,
  Plus,
  Plug,
  RotateCcw,
  Rocket,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldUser,
  SlidersHorizontal,
  Sparkles,
  SquareUserRound,
  Star,
  Target,
  TrendingUp,
  Trash2,
  TriangleAlert,
  User,
  UserCheck,
  Users,
  WandSparkles,
  X,
  type LucideIcon,
} from 'lucide-react';
import type { CSSProperties } from 'react';

const ICON_MAP: Record<string, LucideIcon> = {
  'fa-arrow-down': ArrowDown,
  'fa-arrow-left': ArrowLeft,
  'fa-arrow-right': ArrowRight,
  'fa-ban': Ban,
  'fa-bars': Menu,
  'fa-bell': Bell,
  'fa-book-open': BookOpen,
  'fa-brain': Brain,
  'fa-building': Building2,
  'fa-bullseye': Target,
  'fa-calendar': CalendarDays,
  'fa-chart-bar': BarChart3,
  'fa-chart-line': TrendingUp,
  'fa-chart-pie': PieChart,
  'fa-check': Check,
  'fa-check-circle': CheckCircle2,
  'fa-certificate': Award,
  'fa-chevron-down': ChevronDown,
  'fa-chevron-right': ChevronRight,
  'fa-circle-exclamation': CircleAlert,
  'fa-circle-check': CheckCircle2,
  'fa-circle-notch': LoaderCircle,
  'fa-circle-xmark': CircleX,
  'fa-clock': Clock3,
  'fa-clock-rotate-left': RotateCcw,
  'fa-coins': Coins,
  'fa-comment-dots': MessageCircleMore,
  'fa-cookie-bite': Cookie,
  'fa-cogs': Settings,
  'fa-credit-card': CreditCard,
  'fa-database': Database,
  'fa-child': User,
  'fa-envelope': Mail,
  'fa-exclamation-circle': AlertCircle,
  'fa-external-link-alt': ExternalLink,
  'fa-eye': Eye,
  'fa-eye-slash': EyeOff,
  'fa-gift': Gift,
  'fa-gear': Settings,
  'fa-graduation-cap': GraduationCap,
  'fa-handshake': Handshake,
  'fa-headset': Headset,
  'fa-heart-pulse': HeartPulse,
  'fa-home': Home,
  'fa-info-circle': Info,
  'fa-layer-group': Layers3,
  'fa-list': List,
  'fa-lock': Lock,
  'fa-lock-open': LockKeyholeOpen,
  'fa-location-dot': MapPin,
  'fa-mouse-pointer': MousePointer2,
  'fa-paper-plane': Send,
  'fa-phone': Phone,
  'fa-plug': Plug,
  'fa-plus': Plus,
  'fa-globe': Globe,
  'fa-rocket': Rocket,
  'fa-rotate': RotateCcw,
  'fa-search': Search,
  'fa-share-nodes': Share2,
  'fa-shield-halved': ShieldCheck,
  'fa-sliders': SlidersHorizontal,
  'fa-sign-out-alt': LogOut,
  'fa-spinner': LoaderCircle,
  'fa-sparkles': Sparkles,
  'fa-star': Star,
  'fa-tachometer-alt': LayoutDashboard,
  'fa-times': X,
  'fa-toggle-off': ShieldAlert,
  'fa-toggle-on': Shield,
  'fa-trash': Trash2,
  'fa-triangle-exclamation': TriangleAlert,
  'fa-user': User,
  'fa-user-check': UserCheck,
  'fa-user-circle': User,
  'fa-user-shield': ShieldUser,
  'fa-users': Users,
  'fa-wand-magic-sparkles': WandSparkles,
  'fa-xmark-circle': CircleX,
  'fa-ellipsis': CircleEllipsis,
  'fab fa-github': Globe,
  'fab fa-linkedin-in': ExternalLink,
  'fab fa-paypal': CreditCard,
  'fab fa-x-twitter': ExternalLink,
  success: BadgeCheck,
  book: BookOpen,
  certificate: Award,
  coins: Coins,
  star: Star,
  briefcase: BriefcaseBusiness,
  comments: MessageCircleMore,
  message: MessageCircleMore,
  info: Info,
  default: Circle,
};

export function BrandIcon({
  name,
  className,
  style,
  strokeWidth = 2,
  ariaHidden = true,
}: {
  name: string;
  className?: string;
  style?: CSSProperties;
  strokeWidth?: number;
  ariaHidden?: boolean;
}) {
  const Icon = ICON_MAP[name] || ICON_MAP.default;

  return (
    <Icon
      className={className}
      style={{ width: '1em', height: '1em', ...style }}
      strokeWidth={strokeWidth}
      aria-hidden={ariaHidden}
    />
  );
}
